# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileCopyrightText: 2024 LitterBox-Web contributors

image: docker.io/library/maven:3-eclipse-temurin-21

stages:
  - build
  - test
  - lint
  - nix
  - deploy

include:
  - template: Jobs/Dependency-Scanning.latest.gitlab-ci.yml

.my-rules: &my-rules
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID  # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"  # manual run via GitLab UI

workflow:
  <<: *my-rules

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  MAVEN_ARGS: "--no-transfer-progress -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

################################################################################
# build

build:
  stage: build
  script:
    - mvn compile

################################################################################
# test

test:
  stage: test
  needs:
    - build
  coverage: '/Instruction Coverage: \d+.\d+ %/'
  script:
    - mvn clean test
    - mvn jacoco:report
    - sh ./scripts/coverage.sh $JACOCO_CSV_LOCATION
    - sh ./scripts/coverage_metrics.sh $JACOCO_CSV_LOCATION >> metrics.txt
  variables:
    JACOCO_CSV_LOCATION: "$CI_PROJECT_DIR/target/site/jacoco/jacoco.csv"
  artifacts:
    reports:
      metrics: metrics.txt
      coverage_report:
        coverage_format: jacoco
        path: target/site/jacoco/jacoco.xml
      junit:
        - target/surefire-reports/TEST-*.xml

################################################################################
# lint

.lint: &lint-template
  stage: lint
  needs:
    - build
  rules:
    - if: '$CI_MERGE_REQUEST_TITLE =~ /^(Draft|WIP):/'
      allow_failure: true
    - when: on_success
      allow_failure: false

check-licence-headers:
  <<: *lint-template
  script:
    - mvn license:check

check-licence-headers-reuse:
  <<: *lint-template
  image:
    name: docker.io/fsfe/reuse
    entrypoint: [""]
  script:
    - reuse lint

check-formatting:
  <<: *lint-template
  script:
    - mvn spotless:check

checkstyle:
  <<: *lint-template
  script:
    - mvn checkstyle:check || true
    - cat target/checkstyle-result.xml | ./scripts/checkstyle_report.sh > checkstyle-report.json
  rules:
    - when: on_success
      allow_failure: true
  artifacts:
    when: always
    reports:
      codequality:
        - checkstyle-report.json

################################################################################
# nix

nix-build-jar:
  stage: nix
  needs:
    - build
  image: docker.io/nixos/nix:latest
  script:
    - >
      nix
      --extra-experimental-features nix-command
      --extra-experimental-features flakes
      build
      --print-build-logs
      .#litterbox-web-jar

################################################################################
# deploy

publish-python-packages:
  stage: deploy
  needs: []
  image: docker.io/library/python:latest
  before_script:
    - pip install poetry
    - poetry config repositories.gitlab "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi"
  script:
    - cd connectors/api/
    # generate a unique version number by using the pipeline ID as build number
    # e.g. replaces `version = "0.1.0"` by `version = "0.1.0-1234"` in pyproject.toml
    - sed -i "s#version = \"\(.*\)\"#version = \"\1-${CI_PIPELINE_IID}\"#" pyproject.toml
    - poetry build
    - poetry publish --repository gitlab --username "gitlab-ci-token" --password "${CI_JOB_TOKEN}"
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - changes:
        - connectors/api/**/*
