# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileCopyrightText: 2024 LitterBox-Web contributors

---
image: docker.io/library/maven:3-eclipse-temurin-21

stages:
  - test
  - lint
  - connector-test
  - nix
  - deploy

include:
  - template: Jobs/Dependency-Scanning.latest.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

.my-rules: &my-rules
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID  # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"  # manual run via GitLab UI

workflow:
  <<: *my-rules

variables:
  AST_ENABLE_MR_PIPELINES: "true"
  GIT_SUBMODULE_STRATEGY: recursive
  MAVEN_ARGS: "--no-transfer-progress -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository/
    - litterbox-web/target/

################################################################################
# test

litterbox-web-test:
  stage: test
  needs: []
  coverage: '/Instruction Coverage: \d+.\d+ %/'
  before_script:
    - cd litterbox-web
  script:
    - mvn clean test
    - mvn jacoco:report
  after_script:
    - sh $CI_PROJECT_DIR/scripts/coverage.sh $JACOCO_CSV_LOCATION
    - sh $CI_PROJECT_DIR/scripts/coverage_metrics.sh "litterbox_web" $JACOCO_CSV_LOCATION >> metrics.txt
  variables:
    JACOCO_CSV_LOCATION: "$CI_PROJECT_DIR/litterbox-web/target/site/jacoco/jacoco.csv"
  rules:
    - when: on_success
      allow_failure: false
      changes:
        paths:
          - litterbox-web/**/*
  artifacts:
    reports:
      metrics: metrics.txt
      coverage_report:
        coverage_format: jacoco
        path: litterbox-web/target/site/jacoco/jacoco.xml
      junit:
        - litterbox-web/target/surefire-reports/TEST-*.xml

.python-test: &python-test-template
  stage: connector-test
  image: docker.io/library/python:$PYTHON_VERSION
  before_script:
    - pip install uv
    - cd connectors/$SUBPROJECT
    - uv sync --all-extras --all-groups
  after_script:
    - sed -i "s|/connectors/$SUBPROJECT/src</source>|</source>|" connectors/$SUBPROJECT/coverage.xml
    - sed -i "s|filename=\"|filename=\"connectors/$SUBPROJECT/src/|" connectors/$SUBPROJECT/coverage.xml
  cache: []
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: connectors/$SUBPROJECT/coverage.xml
      junit: connectors/$SUBPROJECT/test-report.xml
  rules:
    - when: on_success
      allow_failure: false
      changes:
        paths:
          - connectors/$SUBPROJECT/**/*

test:code_readability:
  <<: *python-test-template
  parallel:
    matrix:
      - PYTHON_VERSION:
          - "3.13"
  variables:
    MODEL_VERSION_ID: 5
    SUBPROJECT: code_readability
  script:
    - apt-get update
    - apt-get install -y libgl1
    - >
      curl
      --header "Authorization: Bearer $CI_JOB_TOKEN"
      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/ml_models/$MODEL_VERSION_ID/files/pytorch_model.bin"
      >
      pytorch_model.bin
    - >
      MODEL_PATH=$(pwd)/pytorch_model.bin
      uv run pytest
      --junitxml=test-report.xml
      --cov=src --cov=tests --cov-branch
      --cov-report=term-missing --cov-report xml:coverage.xml
      tests

################################################################################
# lint

.lint: &lint-template
  stage: lint
  needs: []
  before_script:
    - cd $SUBDIR
  variables:
    SUBDIR: "litterbox-web"
  rules:
    - if: '$CI_MERGE_REQUEST_TITLE =~ /^(Draft|WIP):/'
      allow_failure: true
    - when: on_success
      allow_failure: false
    - when: on_success
      allow_failure: false
      changes:
        paths:
          - $SUBDIR/**/*

.python-lint: &python-lint-template
  stage: lint
  image: docker.io/library/python:$PYTHON_VERSION
  needs: []
  parallel:
    matrix:
      - PYTHON_VERSION:
          - "3.13"
        SUBPROJECT:
          - api
          - code_completion_dummy
          - code_readability
  before_script:
    - pip install uv
    - cd connectors/$SUBPROJECT
    - uv sync --all-extras --dev
  cache: []
  rules:
    - if: '$CI_MERGE_REQUEST_TITLE =~ /^(Draft|WIP):/'
      allow_failure: true
      changes:
        paths:
          - connectors/$SUBPROJECT/**/*
    - when: on_success
      allow_failure: false
      changes:
        paths:
          - connectors/$SUBPROJECT/**/*

.javascript-lint: &js-lint-template
  stage: lint
  image: docker.io/library/node:$NODE_VERSION
  needs: []
  parallel:
    matrix:
      - NODE_VERSION:
          - "22"
        SUBPROJECT:
          - screenshot
  before_script:
    - cd connectors/$SUBPROJECT
    - npm ci
  cache: []
  rules:
    - if: '$CI_MERGE_REQUEST_TITLE =~ /^(Draft|WIP):/'
      allow_failure: true
      changes:
        paths:
          - connectors/$SUBPROJECT/**/*
    - when: on_success
      allow_failure: false
      changes:
        paths:
          - connectors/$SUBPROJECT/**/*

check-licence-headers:
  <<: *lint-template
  script:
    - mvn license:check

check-licence-headers-reuse:
  <<: *lint-template
  image:
    name: docker.io/fsfe/reuse
    entrypoint: [""]
  cache: []
  script:
    - reuse lint

check-formatting:
  <<: *lint-template
  script:
    - mvn spotless:check

checkstyle:
  <<: *lint-template
  script:
    - mvn checkstyle:check || true
    - cat target/checkstyle-result.xml | $CI_PROJECT_DIR/scripts/checkstyle_report.sh "litterbox-web" > checkstyle-report.json
  rules:
    - when: on_success
      allow_failure: true
  artifacts:
    when: always
    reports:
      codequality:
        - litterbox-web/checkstyle-report.json

python-lint:
  <<: *python-lint-template
  script:
    - uv run isort --check-only .
    - uv run ruff format --diff --check .
    - uv run mypy .
    - uv run ruff check --output-format=gitlab > $CI_PROJECT_DIR/ruff-report.json
  artifacts:
    reports:
      codequality: $CI_PROJECT_DIR/ruff-report.json

js-lint:
  <<: *js-lint-template
  script:
    - npm run lint
    - npm run format:ci

################################################################################
# nix

nix-build-jar:
  stage: nix
  needs: []
  image: docker.io/nixos/nix:latest
  script:
    - >
      nix
      --extra-experimental-features nix-command
      --extra-experimental-features flakes
      build
      --print-build-logs
      .#litterbox-web-jar
  cache: []
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - changes:
        - flake.nix
        - flake.lock
        - litterbox-web/pom.xml
        - litterbox-web/default.nix

nix-files-formatted:
  stage: nix
  needs: []
  image: docker.io/nixos/nix:latest
  script:
    - >
      nix
      --extra-experimental-features nix-command
      --extra-experimental-features flakes
      run
      nixpkgs#alejandra
      .
  cache: []
  rules:
    - changes:
        - "**/*.nix"

################################################################################
# deploy

publish-python-packages:
  stage: deploy
  needs: []
  image: docker.io/library/python:latest
  before_script:
    - pip install uv
  script:
    - cd connectors/api/
    # generate a unique version number by using the pipeline ID as build number
    # e.g. replaces `version = "0.1.0"` by `version = "0.1.0-1234"` in pyproject.toml
    - sed -i "s#version = \"\(.*\)\"#version = \"\1-${CI_PIPELINE_IID}\"#" pyproject.toml
    - uv build
    - uv publish --index litterbox-web-gitlab --username "gitlab-ci-token" --password "${CI_JOB_TOKEN}"
  cache: []
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      changes:
        paths:
          - connectors/api/**/*
