////
  // Copyright (C) 2025 LitterBox-Web contributors
  //
  // This file is part of LitterBox-Web.
  // Licenced under the EUPL-1.2 or later.
  //
  // SPDX-FileCopyrightText: 2024 LitterBox-Web contributors
  // SPDX-License-Identifier: EUPL-1.2
////

= Readme
:icons: font
:lang: en-GB
:sectnums:
:toc:
:xrefstyle: short

// links
:url-litterbox: https://github.com/se2p/litterbox


[abstract]
--
REST API wrapper around link:{url-litterbox}[LitterBox] functionality.
--


== Development


=== Project structure

The package structure and commonly used cross-cutting patterns are described in `Architecture.adoc`.
The main application can be found in the `litterbox-web/` directory.
This directory contains a separate readme file with information on how to build and run the application.

This repository also contains some related projects.
Namely, the `connectors/` directory contains REST-API interfaces to various support tools, like for example a service that can take screenshots of the Scratch workspace.


=== Contribution process

Issues for feature suggestions, bug reports, questions, and other suggestions are always welcome.
Code contributions are welcome, too.

If you want to implement your idea as part of this project and are unsure where/how to do so, please open an issue outlining what you want to achieve.
We can then discuss beforehand what would make the most sense.
This avoids having to spend time on restructuring later-on.

For contributing code, we prefer short-lived branches that each implement a specific feature/bugfix/refactoring.
This makes it easier to merge the branches together, notice when conflicts exist when multiple people work on similar problems, and it makes it easier to fix problems only once for example when updating dependencies.

.Tests
[NOTE]
--
Please add at least some unit/integration tests for your new/changed features.
We do not enforce a minimum coverage.
Do note however, that code not covered by tests may break without notice.
When using the code as part of an experiment or evaluation it should therefore be in your own interest to ensure a reproducibly working implementation.
--


== Licence

Except specific files which bear a different mention, LitterBox-Web is licensed under the EUPL-1.2 or later.
See `LICENSE.txt` or https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12 for more information.


== Publications

* B. Fein, F. Obermüller and G. Fraser, "LitterBox+: An Extensible Framework for LLM-enhanced Scratch Static Code Analysis", in Proceedings of the 40th IEEE/ACM International Conference on Automated Software Engineering (ASE ’25), Tool Demonstration Track. IEEE, 2025. https://doi.org/10.1109/ASE63991.2025.00357 (link:https://arxiv.org/abs/2509.12021[arXiv:2509.12021])
+
The accompanying poster is available at https://doi.org/10.5281/zenodo.17532057.
