= Readme
:icons: font
:lang: en-GB
:sectnums:
:toc:
:xrefstyle: short

// links
:url-litterbox: https://gitlab.infosun.fim.uni-passau.de/se2/litterbox


[abstract]
--
REST API wrapper around link:{url-litterbox}[LitterBox] functionality.
--

== Cloning the repository

LitterBox is included as a submodule.
You either need to clone the repository using
[source,bash]
----
git clone --recurse-submodules URL
----
or run
[source,bash]
----
git submodule update --init
----
afterwards when having cloned without `--recursive`.


== Building

[source,bash]
----
mvn install -DskipTests  # <1>
cd litterbox-web
mvn package spring-boot:repackage
----
<1> Needed for Maven to be able to find the LitterBox dependency in litterbox-web.

Afterwards, you can start the litterbox-web server using
[source,bash]
----
java -jar litterbox-web/target/litterbox-web-${version}.jar
----

Starting the application directly via your IDE from the main class in litterbox-web should also work.

[NOTE]
--
LitterBox is included as a Git submodule.
If the build fails because it cannot find LitterBox (e.g., after the release version changed), you might have to run
[souce,bash]
----
git submodule update --init
----
again.
--


=== Building a container image

[source,bash]
----
mvn spring-boot:build-image
# or for an image that precompiles using GraalVM
mvn spring-boot:build-image -Pnative
----


=== Building a GraalVM binary

[source,bash]
----
mvn native:compile -Pnative
----


== Licence

LitterBox-Web is free software: you can redistribute it and/or modify it under the terms of the GNU General Public Licence as published by the Free Software Foundation, either version 3 of the Licence, or (at your option) any later version.

LitterBox-Web is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public Licence for more details.

You should have received a copy of the GNU General Public Licence along with LitterBox-Web.
If not, see http://www.gnu.org/licenses/.
