////
  // Copyright (C) 2024 LitterBox-Web contributors
  //
  // This file is part of LitterBox-Web.
  //
  // SPDX-FileCopyrightText: 2024 LitterBox-Web contributors
  // SPDX-License-Identifier: GPL-3.0-or-later
  //
  // LitterBox-Web is free software: you can redistribute it and/or modify
  // it under the terms of the GNU General Public Licence as published by
  // the Free Software Foundation, either version 3 of the Licence, or (at
  // your option) any later version.
  //
  // LitterBox-Web is distributed in the hope that it will be useful, but
  // WITHOUT ANY WARRANTY; without even the implied warranty of
  // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  // General Public Licence for more details.
  //
  // You should have received a copy of the GNU General Public Licence
  // along with LitterBox-Web. If not, see <http://www.gnu.org/licenses/>.
////

= Readme
:icons: font
:lang: en-GB
:sectnums:
:toc:
:xrefstyle: short

// links
:url-litterbox: https://gitlab.infosun.fim.uni-passau.de/se2/litterbox


[abstract]
--
REST API wrapper around link:{url-litterbox}[LitterBox] functionality.
--


== Development

=== General

In general, we prefer short-lived branches that each implement a specific feature/bugfix/refactoring.
This makes it easier to merge the branches together, notice when conflicts exist when multiple people work on similar problems, and it makes it easier to fix problems only once when updating dependencies.

[NOTE]
--
Please add at least some tests for your new features so that there is some indication if it still works after other changes.
--


=== Running & Debugging

You can start the application directly in your IDE via the main class `LitterboxWebApplication`.
To enable an automatic reload of the server on code changes, you can start the application with the Spring profile `local` (in IntelliJ Idea: add it to the ‘Active Profiles’ in the run configuration).
In IntelliJ Idea this then also enables an overview of the REST API endpoints in the ‘Actuator’ tab of the ‘Run’ window.

When using the `local` profile, you can also override specific options by editing the `src/main/resources/application-local.yml`.
Once such use-case might be a Scratch-UI running on a non-default port.
In that case add it to the `cors.allowed-origins` list:

.CORS config in `application-local.yml`
[source,yaml]
----
cors:
  allowed-origins:
    - http://localhost:0000
----


== Running the application

=== JAR

[source,bash]
----
mvn package spring-boot:repackage
----

Afterwards, you can start the litterbox-web server using
[source,bash]
----
java -jar litterbox-web/target/litterbox-web-${version}.jar
----


=== Building a container image

[source,bash]
----
mvn spring-boot:build-image
# or for an image that precompiles using GraalVM
mvn spring-boot:build-image -Pnative
----


=== Building a GraalVM binary

[source,bash]
----
mvn native:compile -Pnative
----


== Linting

Licence headers and automatic code formatting are enforced in the CI pipeline.
Checkstyle issues should be checked if useful and usually applied, but might be deemed acceptable/ignorable on a case-by-case basis.
E.g. todo-style comments are shown as warning to make sure you did not forget something before merging but are acceptable to denote that there are going to be follow-up merge requests that implement the missing part.


=== Licence headers

You can automatically add missing licence headers using
[source,bash]
----
mvn license:format
----


=== Code formatting

Automatically format the code and sort imports using
[source,bash]
----
mvn spotless:apply
----


=== Checkstyle

Run the Checkstyle linter using
[source,bash]
----
mvn checkstyle:check
----


== Advanced Topics

=== Using a LitterBox version not available on the `master` branch

The continuous integration of LitterBox only publishes the Maven artifacts for commits on the `master` branch.
In case you need to _temporarily_ use a different branch until it has been merged into `master`, you can use a locally installed LitterBox package:

. Change the version in the `pom.xml` of LitterBox in the relevant branch.
. Run `mvn install` for LitterBox.
    This places the packaged JAR into the local Maven repository (`~/.m2/repository/`).
. You can now change the version of the LitterBox dependency accordingly to use the version you just built.


== Licence

LitterBox-Web is free software: you can redistribute it and/or modify it under the terms of the GNU General Public Licence as published by the Free Software Foundation, either version 3 of the Licence, or (at your option) any later version.

LitterBox-Web is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public Licence for more details.

You should have received a copy of the GNU General Public Licence along with LitterBox-Web.
If not, see http://www.gnu.org/licenses/.
