/*
 * Copyright (C) 2024 LitterBox-Web contributors
 *
 * This file is part of LitterBox-Web.
 * Licenced under the EUPL-1.2 or later.
 *
 * SPDX-FileCopyrightText: 2024 LitterBox-Web contributors
 * SPDX-License-Identifier: EUPL-1.2
 */
package de.uni_passau.fim.se2.litterbox_web.llm;

import java.util.Collections;

import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;

import de.uni_passau.fim.se2.litterbox.analytics.Issue;
import de.uni_passau.fim.se2.litterbox.analytics.llm.LLMIssueEffectExplainer;
import de.uni_passau.fim.se2.litterbox.ast.model.Program;
import de.uni_passau.fim.se2.litterbox.llm.api.LlmApi;
import de.uni_passau.fim.se2.litterbox.llm.prompts.LlmPromptProvider;
import de.uni_passau.fim.se2.litterbox.llm.prompts.PromptBuilder;
import de.uni_passau.fim.se2.litterbox.llm.prompts.QueryTarget;

@Service
@Lazy
public class LlmService {

    private final LlmApi llmApi;

    private final PromptBuilder promptBuilder = LlmPromptProvider.get();

    public LlmService(final LlmApi llmApi) {
        this.llmApi = llmApi;
    }

    /**
     * Asks the LLM to explain the issue in more detail.
     *
     * @param program The program the issue appears in.
     * @param sprite  The sprite the issue appears in.
     * @param issue   The issue that should be explained in more detail.
     * @return An extended issue hint generated by the LLM.
     */
    public String getIssueExplanation(final Program program, final String sprite, final Issue issue) {
        final LLMIssueEffectExplainer explainer = new LLMIssueEffectExplainer(
            llmApi, promptBuilder, new QueryTarget.SpriteTarget(sprite)
        );
        final Issue newIssue = explainer.apply(program, Collections.singleton(issue)).stream()
            .findFirst()
            .orElseThrow();
        return newIssue.getHintText();
    }
}
