/*
 * Copyright (C) 2024 LitterBox-Web contributors
 *
 * This file is part of LitterBox-Web.
 * Licenced under the EUPL-1.2 or later.
 *
 * SPDX-FileCopyrightText: 2024 LitterBox-Web contributors
 * SPDX-License-Identifier: EUPL-1.2
 */
package de.uni_passau.fim.se2.litterbox_web.llm;

import java.util.Collections;

import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;

import de.uni_passau.fim.se2.litterbox.analytics.Hint;
import de.uni_passau.fim.se2.litterbox.analytics.Issue;
import de.uni_passau.fim.se2.litterbox.analytics.IssueBuilder;
import de.uni_passau.fim.se2.litterbox.analytics.IssueTool;
import de.uni_passau.fim.se2.litterbox.analytics.llm.LLMIssueEffectExplainer;
import de.uni_passau.fim.se2.litterbox.ast.model.ActorDefinition;
import de.uni_passau.fim.se2.litterbox.ast.model.Program;
import de.uni_passau.fim.se2.litterbox.ast.model.Script;
import de.uni_passau.fim.se2.litterbox.ast.util.AstNodeUtil;
import de.uni_passau.fim.se2.litterbox.ast.visitor.BlockByIdFinder;
import de.uni_passau.fim.se2.litterbox.llm.api.LlmApi;
import de.uni_passau.fim.se2.litterbox.llm.prompts.LlmPromptProvider;
import de.uni_passau.fim.se2.litterbox.llm.prompts.PromptBuilder;
import de.uni_passau.fim.se2.litterbox.llm.prompts.QueryTarget;
import de.uni_passau.fim.se2.litterbox_web.shared.dto.IssueDTO;

@Service
@Lazy
public class LlmService {

    private final LlmApi llmApi;

    private final PromptBuilder promptBuilder = LlmPromptProvider.get();

    public LlmService(final LlmApi llmApi) {
        this.llmApi = llmApi;
    }

    /**
     * Asks the LLM to explain the issue in more detail.
     *
     * @param program  The program the issue appears in.
     * @param issueDto The issue that should be explained in more detail.
     * @return An extended issue hint generated by the LLM.
     */
    public IssueDTO getIssueExplanation(final Program program, final IssueDTO issueDto) {
        final LLMIssueEffectExplainer explainer = new LLMIssueEffectExplainer(
            llmApi, promptBuilder, new QueryTarget.SpriteTarget(issueDto.sprite())
        );
        final Issue issue = fromIssueDto(program, issueDto);
        final Issue newIssue = explainer.apply(program, Collections.singleton(issue)).stream()
            .findFirst()
            .orElseThrow();
        return issueDto.withExplanation(newIssue.getHintText());
    }

    private Issue fromIssueDto(final Program program, final IssueDTO issueDTO) {
        final ActorDefinition actor = AstNodeUtil.findActorByName(program, issueDTO.sprite());

        IssueBuilder issueBuilder = new IssueBuilder()
            .withId(issueDTO.id())
            .withActor(actor)
            .withHint(Hint.fromText(issueDTO.issueHint()))
            .withFinder(
                IssueTool.getFinders(issueDTO.finderName()).stream().findFirst().orElse(null)
            );

        if (issueDTO.blockId() != null) {
            issueBuilder = issueBuilder.withCurrentNode(
                BlockByIdFinder.findBlock(actor, issueDTO.blockId()).orElse(null)
            );
        }
        if (issueDTO.hatBlockId() != null) {
            final Script script = BlockByIdFinder.findBlock(actor, issueDTO.hatBlockId())
                .map(hat -> AstNodeUtil.findParent(hat, Script.class))
                .orElse(null);
            issueBuilder = issueBuilder.withScript(script);
        }

        return issueBuilder.build();
    }
}
