# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileCopyrightText: 2024 LitterBox-Web contributors

litterbox-web:
  code-completion:
    models:
      transformer:
        url: http://localhost:8081/
      n-gram:
        url: http://localhost:8000/code-completion
