/*
 * Copyright (C) 2024 LitterBox-Web contributors
 *
 * This file is part of LitterBox-Web.
 * Licenced under the EUPL-1.2 or later.
 *
 * SPDX-FileCopyrightText: 2024 LitterBox-Web contributors
 * SPDX-License-Identifier: EUPL-1.2
 */
package de.uni_passau.fim.se2.litterbox_web.llm;

import java.util.Collections;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

import org.jspecify.annotations.Nullable;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;

import de.uni_passau.fim.se2.litterbox.analytics.Hint;
import de.uni_passau.fim.se2.litterbox.analytics.Issue;
import de.uni_passau.fim.se2.litterbox.analytics.IssueBuilder;
import de.uni_passau.fim.se2.litterbox.analytics.IssueTool;
import de.uni_passau.fim.se2.litterbox.analytics.llm.LLMIssueEffectExplainer;
import de.uni_passau.fim.se2.litterbox.analytics.llm.LLMProgramFixAnalyzer;
import de.uni_passau.fim.se2.litterbox.analytics.llm.LLMProgramQueryAnalyzer;
import de.uni_passau.fim.se2.litterbox.ast.model.ActorDefinition;
import de.uni_passau.fim.se2.litterbox.ast.model.Program;
import de.uni_passau.fim.se2.litterbox.ast.model.Script;
import de.uni_passau.fim.se2.litterbox.ast.util.AstNodeUtil;
import de.uni_passau.fim.se2.litterbox.ast.visitor.BlockByIdFinder;
import de.uni_passau.fim.se2.litterbox.llm.api.LlmApi;
import de.uni_passau.fim.se2.litterbox.llm.prompts.LlmPromptProvider;
import de.uni_passau.fim.se2.litterbox.llm.prompts.LlmQuery;
import de.uni_passau.fim.se2.litterbox.llm.prompts.PromptBuilder;
import de.uni_passau.fim.se2.litterbox.llm.prompts.QueryTarget;
import de.uni_passau.fim.se2.litterbox.utils.IssueTranslator;
import de.uni_passau.fim.se2.litterbox.utils.IssueTranslatorFactory;
import de.uni_passau.fim.se2.litterbox_web.shared.dto.IssueDTO;

@Lazy
@Service
public class LlmService {

    private final LlmApi llmApi;

    private final Map<Locale, PromptBuilder> promptBuilders = new ConcurrentHashMap<>();

    public LlmService(final LlmApi llmApi) {
        this.llmApi = llmApi;
    }

    private PromptBuilder getPromptBuilder(final Locale locale) {
        return promptBuilders.computeIfAbsent(
            locale,
            l -> LlmPromptProvider.get(IssueTranslatorFactory.getIssueTranslator(locale))
        );
    }

    /**
     * Asks the LLM to explain the issue in more detail.
     *
     * @param locale   The language for responses.
     * @param program  The program the issue appears in.
     * @param issueDto The issue that should be explained in more detail.
     * @return An extended issue hint generated by the LLM.
     */
    public IssueDTO getIssueExplanation(final Locale locale, final Program program, final IssueDTO issueDto) {
        final IssueTranslator translator = IssueTranslatorFactory.getIssueTranslator(locale);
        final PromptBuilder promptBuilder = getPromptBuilder(locale);

        final LLMIssueEffectExplainer explainer = new LLMIssueEffectExplainer(
            translator, llmApi, promptBuilder, new QueryTarget.SpriteTarget(issueDto.sprite())
        );
        final Issue issue = fromIssueDto(program, issueDto);
        final Issue newIssue = explainer.apply(program, Collections.singleton(issue)).stream()
            .findFirst()
            .orElseThrow();
        return issueDto.withExplanation(newIssue.getHintText(translator));
    }

    private Issue fromIssueDto(final Program program, final IssueDTO issueDto) {
        final ActorDefinition actor = AstNodeUtil.findActorByName(program, issueDto.sprite());

        IssueBuilder issueBuilder = new IssueBuilder()
            .withId(issueDto.id())
            .withActor(actor)
            .withHint(Hint.fromText(issueDto.hint()))
            .withFinder(
                IssueTool.getFinders(issueDto.name()).stream().findFirst().orElse(null)
            );

        if (actor != null && issueDto.blockId() != null) {
            issueBuilder = issueBuilder.withCurrentNode(
                BlockByIdFinder.findBlock(actor, issueDto.blockId()).orElse(null)
            );
        }
        if (actor != null && issueDto.hatBlockId() != null) {
            final Script script = BlockByIdFinder.findBlock(actor, issueDto.hatBlockId())
                .map(hat -> AstNodeUtil.findParent(hat, Script.class))
                .orElse(null);
            issueBuilder = issueBuilder.withScript(script);
        }

        return issueBuilder.build();
    }

    /**
     * Asks the LLM the given question either with the context of the program or just the sprite.
     *
     * @param locale   The language for the response.
     * @param program  A Scratch program.
     * @param sprite   The sprite the question is about. Optional.
     * @param question The question for the LLM.
     * @return The LLM response.
     */
    public String respondToQuestion(
        final Locale locale, final Program program, @Nullable final String sprite, final String question
    ) {
        final PromptBuilder promptBuilder = getPromptBuilder(locale);

        final LlmQuery query = new LlmQuery.CustomQuery(question);
        final QueryTarget target = targetFromSpriteName(sprite);

        final LLMProgramQueryAnalyzer analyzer = new LLMProgramQueryAnalyzer(
            llmApi, promptBuilder, query, target, false
        );
        return analyzer.analyze(program);
    }

    /**
     * Tries to fix the given issue within the program.
     *
     * @param locale   The language of the response.
     * @param program  A Scratch program.
     * @param issueDto The issue that should be fixed.
     * @return The program including the proposed fix.
     */
    public Program fixIssue(final Locale locale, final Program program, final IssueDTO issueDto) {
        final PromptBuilder promptBuilder = getPromptBuilder(locale);

        final Issue issue = fromIssueDto(program, issueDto);
        final QueryTarget target = targetFromIssue(issueDto);
        final LLMProgramFixAnalyzer analyzer = new LLMProgramFixAnalyzer(
            llmApi, promptBuilder, target, Collections.singleton(issue)
        );

        return analyzer.analyze(program);
    }

    private QueryTarget targetFromSpriteName(@Nullable final String sprite) {
        if (sprite == null) {
            return new QueryTarget.ProgramTarget();
        }
        else {
            return new QueryTarget.SpriteTarget(sprite);
        }
    }

    private QueryTarget targetFromIssue(final IssueDTO issueDTO) {
        if (issueDTO.hatBlockId() != null) {
            return new QueryTarget.ScriptTarget(issueDTO.hatBlockId());
        }
        else if (issueDTO.sprite() != null) {
            return new QueryTarget.SpriteTarget(issueDTO.sprite());
        }
        else {
            return new QueryTarget.ProgramTarget();
        }
    }
}
