# SPDX-FileCopyrightText: 2025 LitterBox-Web contributors
#
# SPDX-License-Identifier: EUPL-1.2

SPACE = (255, 255, 255)

MOTION_BLOCK = (76, 151, 255)
MOTION_SELECT = (66, 128, 215)
MOTION_INPUT = (250, 250, 250)

LOOKS_BLOCK = (153, 102, 255)
LOOKS_SELECT = (133, 92, 214)
LOOKS_INPUT = (245, 245, 245)

SOUND_BLOCK = (207, 99, 207)
SOUND_SELECT = (201, 79, 201)
SOUND_INPUT = (240, 240, 240)

EVENT_BLOCK = (255, 191, 0)
EVENT_SELECT = (230, 172, 0)
EVENT_INPUT = (235, 235, 235)

CONTROL_BLOCK = (255, 171, 25)
CONTROL_SELECT = (236, 156, 19)
CONTROL_PLACEHOLDER = (207, 139, 23)
CONTROL_INPUT = (230, 230, 230)

SENSING_BLOCK = (92, 177, 214)
SENSING_SELECT = (71, 168, 209)
SENSING_INPUT = (225, 225, 225)
SENSING_COLOR_INPUT = (220, 220, 220)

OPERATOR_BLOCK = (89, 192, 89)
OPERATOR_PLACEHOLDER = (56, 148, 56)
OPERATOR_INPUT = (215, 215, 215)

VARIABLE_BLOCK = (255, 140, 26)
VARIABLE_INPUT = (210, 210, 210)

CUSTOM_BLOCK = (255, 102, 128)
CUSTOM_DEFINITION = (255, 77, 106)
CUSTOM_BOOL_INPUT = (255, 51, 85)
CUSTOM_INPUT = (205, 205, 205)

EXTENSION_BLOCK = (15, 189, 140)
EXTENSION_SELECT = (13, 165, 122)
EXTENSION_INPUT = (200, 200, 200)
EXTENSION_COLOR_INPUT = (195, 195, 195)

BLOCK_COLORS = {
    "MOTION": {MOTION_BLOCK, MOTION_SELECT, MOTION_INPUT},
    "LOOKS": {LOOKS_BLOCK, LOOKS_SELECT, LOOKS_INPUT},
    "SOUND": {SOUND_BLOCK, SOUND_SELECT, SOUND_INPUT},
    "EVENT": {EVENT_BLOCK, EVENT_SELECT, EVENT_INPUT},
    "CONTROL": {CONTROL_BLOCK, CONTROL_SELECT, CONTROL_PLACEHOLDER, CONTROL_INPUT},
    "SENSING": {SENSING_BLOCK, SENSING_SELECT, SENSING_INPUT, SENSING_COLOR_INPUT},
    "OPERATOR": {OPERATOR_BLOCK, OPERATOR_PLACEHOLDER, OPERATOR_INPUT},
    "VARIABLE": {VARIABLE_BLOCK, VARIABLE_INPUT},
    "CUSTOM": {CUSTOM_BLOCK, CUSTOM_DEFINITION, CUSTOM_BOOL_INPUT, CUSTOM_INPUT},
    "EXTENSION": {
        EXTENSION_BLOCK,
        EXTENSION_SELECT,
        EXTENSION_INPUT,
        EXTENSION_COLOR_INPUT,
    },
}

CATEGORY_COLORS = {
    "BLOCK": {
        MOTION_BLOCK,
        LOOKS_BLOCK,
        SOUND_BLOCK,
        EVENT_BLOCK,
        CONTROL_BLOCK,
        SENSING_BLOCK,
        OPERATOR_BLOCK,
        VARIABLE_BLOCK,
        CUSTOM_BLOCK,
        EXTENSION_BLOCK,
    },
    "SELECT": {
        MOTION_SELECT,
        LOOKS_SELECT,
        SOUND_SELECT,
        EVENT_SELECT,
        CONTROL_SELECT,
        SENSING_SELECT,
        EXTENSION_SELECT,
    },
    "PLACEHOLDER": {
        MOTION_INPUT,
        LOOKS_INPUT,
        SOUND_INPUT,
        EVENT_INPUT,
        CONTROL_INPUT,
        CONTROL_PLACEHOLDER,
        SENSING_INPUT,
        SENSING_COLOR_INPUT,
        OPERATOR_INPUT,
        OPERATOR_PLACEHOLDER,
        VARIABLE_INPUT,
        CUSTOM_INPUT,
        CUSTOM_BOOL_INPUT,
        EXTENSION_INPUT,
        EXTENSION_COLOR_INPUT,
    },
    "DEFINITION": {CUSTOM_DEFINITION},
}

TAG_COLORS = {**BLOCK_COLORS, **CATEGORY_COLORS}

ALL_TAGS = list(TAG_COLORS.keys())


def rgb_to_hex(color: tuple[int, int, int]) -> str:
    return "#{:02x}{:02x}{:02x}".format(*color)
