# SPDX-FileCopyrightText: 2025 LitterBox-Web contributors
#
# SPDX-License-Identifier: EUPL-1.2

SPACE = (255, 255, 255)

MOTION_BLOCK = (76, 151, 255)
MOTION_SELECT = (66, 128, 215)

LOOKS_BLOCK = (153, 102, 255)
LOOKS_SELECT = (133, 92, 214)

SOUND_BLOCK = (207, 99, 207)
SOUND_SELECT = (201, 79, 201)

EVENT_BLOCK = (255, 191, 0)
EVENT_SELECT = (230, 172, 0)

CONTROL_BLOCK = (255, 171, 25)
CONTROL_SELECT = (236, 156, 19)
CONTROL_PLACEHOLDER = (207, 139, 23)

SENSING_BLOCK = (92, 177, 214)
SENSING_SELECT = (71, 168, 209)

OPERATOR_BLOCK = (89, 192, 89)
OPERATOR_PLACEHOLDER = (56, 148, 56)

VARIABLE_BLOCK = (255, 140, 26)

CUSTOM_BLOCK = (255, 102, 128)
CUSTOM_DEFINITION = (255, 77, 106)
CUSTOM_BOOL_INPUT = (255, 51, 85)

EXTENSION_BLOCK = (15, 189, 140)
EXTENSION_SELECT = (13, 165, 122)

COLOR_BLOCK_MAPPING: dict[tuple[int, int, int], str] = {
    MOTION_BLOCK: "MOTION_BLOCK",
    MOTION_SELECT: "MOTION_SELECT",
    LOOKS_BLOCK: "LOOKS_BLOCK",
    LOOKS_SELECT: "LOOKS_SELECT",
    SOUND_BLOCK: "SOUND_BLOCK",
    SOUND_SELECT: "SOUND_SELECT",
    EVENT_BLOCK: "EVENT_BLOCK",
    EVENT_SELECT: "EVENT_SELECT",
    CONTROL_BLOCK: "CONTROL_BLOCK",
    CONTROL_SELECT: "CONTROL_SELECT",
    CONTROL_PLACEHOLDER: "CONTROL_PLACEHOLDER",
    SENSING_BLOCK: "SENSING_BLOCK",
    SENSING_SELECT: "SENSING_SELECT",
    OPERATOR_BLOCK: "OPERATOR_BLOCK",
    OPERATOR_PLACEHOLDER: "OPERATOR_PLACEHOLDER",
    VARIABLE_BLOCK: "VARIABLE_BLOCK",
    CUSTOM_BLOCK: "CUSTOM_BLOCK",
    CUSTOM_DEFINITION: "CUSTOM_DEFINITION",
    CUSTOM_BOOL_INPUT: "CUSTOM_BOOL_INPUT",
    EXTENSION_BLOCK: "EXTENSION_BLOCK",
    EXTENSION_SELECT: "EXTENSION_SELECT",
}

BLOCK_COLOR_MAPPING: dict[str, tuple[int, int, int]] = dict(
    [(v, k) for k, v in COLOR_BLOCK_MAPPING.items()]
)
BLOCKS = list(COLOR_BLOCK_MAPPING.values())
